title: Emil Konstantinovitz
email: emil.konstantinovitz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a young aspiring data scientist. To me this isn't just my job, but my hobby, my dream, I live and
  breathe for this.
  Send me a mail if you'd be interestet in working with me.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: konstantinovitz
github_username:  yunderboy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
